version: '3.7'

services:

  # PHP Service
  php-fpm:
    image: php:8.1-rc-fpm-bullseye
    container_name: php
    ports:
      - "9000:9000"
    working_dir: /var/www
    volumes:
      - ./www/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  # PostgreSQL Service
  db:
    image: postgres:12.2-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
